# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


 np.zeros陣列中每個元素都是0 np.empty則是接近0 
 另外np.empty比較快取得亂數

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [5]:
# 參考解答
import numpy as np 
a = np.random.rand(2, 3)
a*=100
'''
Your Code
'''
print(a.round())

[[17. 40. 92.]
 [79. 39. 44.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [8]:
m = 20
n = 40

'''
Your Code
'''
#將(0,20)及(1,40)解線性方程
b=((n-m)/100)*a+m
print(b.round(0))

[[23. 28. 38.]
 [36. 28. 29.]]
