# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [7]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [4]:
'''
Your Code
'''
import numpy as np
array=np.arange(10)
array[3:7]=-(array[3:7])
print(array)

[ 0  1  2 -3 -4 -5 -6  7  8  9]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [10]:
A = np.random.rand(3, 6)

'''
Your Code
'''
print(A)
print(A[A>0.5].size)

[[0.54776216 0.28023543 0.16684055 0.51866048 0.93734436 0.59621665]
 [0.26472794 0.99676697 0.19839362 0.98877634 0.78385219 0.6030011 ]
 [0.80863945 0.01680996 0.22605254 0.43662802 0.46498661 0.55991282]]
10
