# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [7]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [4]:
'''
Your Code
'''
import numpy as np
array=np.arange(10)
array[3:7]=-(array[3:7])
print(array)

[ 0  1  2 -3 -4 -5 -6  7  8  9]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [6]:
A = np.random.rand(3, 6)

'''
Your Code
'''
print(A)
print(A[A>0.5])

[[0.6511918  0.68841763 0.48450067 0.93341385 0.20899198 0.77491883]
 [0.96593599 0.23262324 0.84616066 0.13453182 0.6671731  0.54559091]
 [0.38339591 0.65047864 0.67136834 0.59788965 0.42303315 0.61969397]]
[0.6511918  0.68841763 0.93341385 0.77491883 0.96593599 0.84616066
 0.6671731  0.54559091 0.65047864 0.67136834 0.59788965 0.61969397]
